name: Docs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  docs:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Pages
      uses: actions/configure-pages@v3
    - name: Generate Docs
      uses: fwcd/swift-docc-action@v1
      with:
        target: NostrSDK
        output: ./docs
        transform-for-static-hosting: 'true'
        disable-indexing: 'true'
        hosting-base-path: nostr-sdk-ios 
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: docs

    steps:
    - name: Deploy Docs
      uses: actions/deploy-pages@v1