name: Unit Tests

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: macos-latest
    strategy:
      matrix:
        swift: ['5.8', '5.9', '5.10']

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Swift
      uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: ${{ matrix.swift }}

    - name: Build and Test
      run: |
        swift build
        swift test
